# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: server build

on:
  push:
    paths:
      - '*/**'  # matches changes that aren't top level
      - '!client/**'  # excludes changes to the client
      - '!.github/**client**'  # exclude changes to client workflows
      - 'pom.xml'  # make sure to detect changes to the pom
    branches: [ main ]
  pull_request:
    paths:
      - '*/**'  # matches changes that aren't top level
      - '!client/**'  # excludes changes to the client
      - 'pom.xml'  # make sure to detect changes to the pom
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build Server Package
      run: mvn -B package --file pom.xml
